name: Android Pull Request CI

on:
  pull request:
    push:
      branches:
        - 'master'

  workflow_dispatch:

jobs:

  code-analysis:
    name: Run Detekt for static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2.3.3
      - name: Setup JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Run Detekt
        run: bash ./gradlew detekt
  test:
    name: Run unit and instrumented tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit Test with Android Emulator Runner
          uses: ReactiveCircus/android-emulator-runner@v2.14.3
          with:
            api-level: 29
            script: ./gradlew connectedCheck

              run: ./gradlew testDebugUnitTest

                - name: Generate Jacoco Report
                  uses: actions/upload-artifact@v2
                  with:
                    name: report
                    path: app/build/reports/coverage/debug

                - name: Download Test Reports Folder
                  uses: actions/download-artifact@v2
                  with:
                    name: report
                    path: app/build/reports/coverage/debug

                - name: Upload Test Report
                  run: bash <(curl -s https://codecov.io/bash) -f "app/build/reports/coverage/debug/report.xml"
