name: Android Pull Request CI

on:
  pull_request:
    push:
      branches:
        - 'master'

  workflow_dispatch:

jobs:
  code-analysis:
    name: Run Detekt for static code analysis
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Detekt
        run: bash ./gradlew detekt
  test:
    name: Run all module unit tests and check test coverage
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 23
          target: default
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck
      - name: Generate Jacoco test report
        run: bash ./gradlew jacocoTestReport
      - name: Check code coverage
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f build/reports/jacoco/jacocoTestReport.xml
