name: Android Tag CI Configuration

on:
  push:
    tags:
      - '*'

jobs:
  upload-apk:
    name: Generate and upload APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Set up JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Generate APK
        run: bash ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
